#!/bin/bash
### BEGIN INIT INFO
# Provides: containerd
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop containers service
### END INIT INFO

set -eufo pipefail

DESC="container daemon"
NAME="containerd"
PIDFILE="/var/run/containerd.pid"
touch $PIDFILE
KPID=$(cat $PIDFILE)

do_start() {
    touch $PIDFILE
    if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
      logger -t info [$NAME] $NAME already running
    else
      docker system prune -f
      cd /var/tmp/image
      export RANDOM_PASSWORD=$(sort -R /usr/share/dict/words | head -1)
      export RANDOM_NAME=$(sort -R /usr/share/dict/words | head -1 | tr -d "'")
      docker-compose up --build &
      echo $! > $PIDFILE
    fi
}

do_stop() {
 echo "Stopping $NAME";
 if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
       logger -t info [$NAME] $NAME already running
     kill $KPID
     cd /var/tmp/image
     docker-compose stop
 fi
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   restart)
     do_stop
     do_start
     ;;
   *)
     echo "Usage: /etc/init.d/$NAME start|stop"
     exit 1
     ;;
esac

exit 0

