version: "2"

services:
  ssh:
    build:
      context: . #current dir as build context
      args:
        PASSWORD_GENERATED: ${RANDOM_PASSWORD}
    image: ssh
    ports:
      - "22:22"
    container_name: ssh
    hostname: ${RANDOM_NAME}
    domainname: superprivy.com
    networks:
      - ssh

networks:
  ssh:
    driver: bridge

#   ssh needs a fair amount of capabilities.
#    cap_drop:
#      - ALL
#
#    cap_add:
#      - AUDIT_WRITE
#      - NET_BIND_SERVICE
#      - NET_RAW
#      - SYS_CHROOT

