#!/bin/bash
### BEGIN INIT INFO
# Provides: sysdigd
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop service sysdigd
### END INIT INFO


DESC="sysdig daemon"
NAME="sysdig"
PIDFILE="/var/run/sysdigd.pid"
KPID=$(cat $PIDFILE)

do_start() {
    if [ ! -d /var/log/traces ];then
        logger -t info "creating traces directory"
        mkdir -p /var/log/traces
    fi

    if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
        logger -t info [sysdigd] sysdig already running
    else
        bash -c 'sysdig -F -C 200 -G 300 -W 5 -z -w /var/log/traces/$(hostname).%F-%H-%M.part > /dev/null 2>&1 &'
        PID=$(pidof sysdig)
        if [ -z "$PID" ];then
            logger -t error [sysdigd] something went wrong, unable to launch sysdig
            exit 2
        else
            echo $PID > /var/run/sysdigd.pid
        fi
    fi
}

do_stop() {
 echo "Stopping $NAME";
     PID=$(pidof sysdig)
     if [ ! -z "$PID" ];then
        kill $PID
     fi
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   *)
     echo "Usage: /etc/init.d/mysysdig start|stop"
     exit 1
     ;;
esac

exit 0

