# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.



Vagrant.configure(2) do |config|


   config.ssh.username = "root"
   config.ssh.private_key_path = "/home/fsero/.ssh/id_dsa"


   config.vm.define "sinker" do |v|
       v.vm.provider "docker" do |d|
           d.build_dir = "/home/fsero/repos/b/pfc/vagrant_docker"
           d.build_args = ["-t", "sinker"]
           d.name = "sinker"
           d.remains_running = false
           d.create_args = ["-p","2202:22","-it", "--privileged"]
       end
   end

   config.vm.define "main" do |v|
       v.vm.provider "docker" do |d|
           d.build_dir = "/home/fsero/repos/b/pfc/vagrant_docker"
           d.build_args = ["-t", "main"]
           d.name = "main"
           d.remains_running = false
           d.create_args = ["-p","2201:22","-it", "--privileged"]
       end
   end
   
    config.vm.define "pki" do |v|
          v.vm.provider "docker" do |d|
              d.build_dir = "/home/fsero/repos/b/pfc/vagrant_docker"
              d.build_args = ["-t", "pki"]
              d.name = "pki"
              d.remains_running = false
              d.create_args = ["-p","2200:22", "-it", "--privileged"]
          end
    end
end
