---
- name: restart sysdigd
  systemd:
    state: restarted
    name: sysdigd
    daemon_reload: yes
    enabled: yes

- name: restart falco
  systemd:
    state: restarted
    name: falco
    daemon_reload: yes
    enabled: yes
