---
galaxy_info:
  author: Chris Spicer
  description: Ansible role for managing apt repositories and keeping the local apt cache up to date
  license: MIT
  min_ansible_version: 1.8
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Ubuntu
      versions:
        - precise
        - trusty
  categories:
  - development
  - packaging
  - system
allow_duplicates: yes
dependencies: []
