- hosts: 'newjoiners'
  roles:
      - { role: dev-sec.ssh-hardening }
  tasks:

  - name: 'install whois'
    apt: name=whois state=present

  - name: Generate password for new user
    shell: /usr/bin/openssl rand -base64 32
    register: user_password

  - name: Generate encrypted password
    shell: mkpasswd --method=SHA-512 {{ user_password.stdout }}
    register: encrypted_user_password

  - name: creating ansible user
    user:
      name: joe
      shell: /bin/bash
      groups: sudo
      password: "{{ encrypted_user_password.stdout }}"
      append: yes
      update_password: 'on_create'
    register: newuser

  - name: Set authorized key took from file
    authorized_key:
      user: joe
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: create a sudoers files
    blockinfile:
      name: /etc/sudoers.d/joe
      create: yes
      insertafter: 'EOF'
      owner: root
      group: root
      mode: 0644
      block: |
        Defaults:joe !requiretty
        joe ALL=(ALL) NOPASSWD: ALL
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
    notify:
      - restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted