- hosts: 'main'
  roles:
      - { role: ansible-docker, become: true, when: ansible_os_family == 'Debian' }
      - { role: debops.pki, become: true, when: ansible_os_family == 'Debian' }
      - role: debops.rsyslog
        rsyslog__capabilities: ['tls', 'network', 'remote-files']
        become: true
        when: ansible_os_family == 'Debian'
      - role: debops.core
        tags: [ 'role::core' ]
        become: True
      - role: debops.secret
        tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
        secret_directories:
          - '{{ pki_env_secret_directories }}'

      - role: debops.pki
        tags: [ 'role::pki', 'role::pki:secret', 'role::secret' ]

