- hosts: 'sinkers'
  roles:
      - { role: ansible-docker, become: true, when: ansible_os_family == 'Debian' }
      - role: debops.rsyslog
        rsyslog__capabilities: ['tls']
        rsyslog__forward: [ '*.* @@192.168.33.11:6514' ]
        become: true
        when: ansible_os_family == 'Debian'
      - role: debops.core
        tags: [ 'role::core' ]
        become: True
      - role: debops.secret
        tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
        secret_directories:
          - '{{ pki_env_secret_directories }}'

      - role: debops.pki
        tags: [ 'role::pki', 'role::pki:secret', 'role::secret' ]
      #- { role: freedomofpress.grsecurity/roles/install-grsec-kernel,
      #  become: true,
      #  when: ansible_os_family == 'Debian',
      #  grsecurity_install_deb_package: files/linux-image-4.4.6-grsec_4.4.6-grsec-10.00.Custom_amd64.deb }
            
  pre_tasks:
     - include: tasks/install_latest_pip.yml    
       when: ansible_os_family == "Debian"
  
  post_tasks:
  
     - include: tasks/install_sysdig.yml
       when: ansible_os_family == "Debian"
