---
sysdig_repo_key_url: "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
sysdig_repo_key_id: "EC51E8C4"

sysdig_files:
  - { src: '../files/sysdigd', dest: '/usr/local/sbin/sysdigd', mode: '0500' }
  - { src: '../files/cleanup_traces.sh', dest: '/usr/local/sbin/cleanup_traces.sh', mode: '0500' }
  - { src: '../files/sysdigd.service', dest: '/etc/systemd/system/sysdigd.service', mode: '0444' }

falco_files:
  - { src: '../files/falco.yaml', dest: '/etc/falco.yaml', mode: '0444' }
  - { src: '../files/falco_container_rules.yaml', dest: '/etc/falco_container_rules.yaml', mode: '0444' }
  - { src: '../files/falco.service', dest: '/etc/systemd/system/falco.service', mode: '0444' }



container_directory: "/var/tmp/image"

container_files:
  - { src: '../files/Dockerfile', dest: "{{ container_directory }}/Dockerfile", mode: '0500' }
  - { src: '../files/docker-compose.yml', dest: "{{ container_directory }}/docker-compose.yml", mode: '0500' }
  - { src: '../files/tc_manager.sh', dest: '/usr/local/sbin/tc_manager.sh', mode: '0500' }
  - { src: '../files/containerd', dest: '/usr/local/sbin/containerd', mode: '0500' }
  - { src: '../files/containerd.service', dest: '/etc/systemd/system/containerd.service', mode: '0444' }


