---
- name: main | apt-cache update
  apt:
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: main | install ansible apt dependencies
  action: apt pkg={{ item }} state=latest
  with_items: apt_pkg

- name: main | add repository
  apt_repository: "repo='{{ item.repo_url }}' state=present"
  with_items: apt_repo
  when: apt_repo is defined
  register: apt_require_update

- name: main | add repository key via keyserver
  apt_key:
    id='{{ item.key_id }}'
    keyserver='{{ item.key_server }}'
    state=present
  with_items: apt_repo
  when: item.key_id and item.key_server is defined
  register: apt_added_keyserver

- name: main | add repository key via url
  apt_key:
    id='{{ item.key_id }}'
    url='{{ item.key_url }}'
    state=present
  with_items: apt_repo
  when: item.key_id and item.key_url is defined
  register: apt_added_url

- name: main | apt-cache update (changed)
  apt: update_cache=yes
  when: apt_added_keyserver | changed or apt_added_url | changed or apt_require_update | changed
